#!/bin/sh

# ~/.scripts/lock
# Locks the screen. The STATUS_COMMAND environment variable is used to determine
# the status command.

kill -0 "$(cat "$XDG_CACHE_HOME/lock_pid")" 2> /dev/null && exit

# Using TIFF format as ImageMagick seems to write it a lot faster than PNG.
image="$(mktemp lock-wallpaper.XXXXXXXXXX.tiff)"
convert "$XDG_CONFIG_HOME/wallpaper" +level 0%,20% "$image"

swaymsg bar 0 status_command "$STATUS_COMMAND"

swayidle timeout 30 'systemctl suspend' &
swayidle_pid="$!"

{
  swaylock -i "$image" &
  echo "$!" > "$XDG_CACHE_HOME/lock_pid"
  wait "$!"
  kill -- "$swayidle_pid"
  rm "$image"
  rm "$XDG_CACHE_HOME/lock_pid"
} &

sleep 1
